### ISSUE TITLE
Restore functionality of reflect_flat_test

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#149]
We commented out reflect_flat_test when we changed the reverberation calculations.  In addition to its original functionality, it had been augmented to also test reverberation collisions. In the mean time, the reverberation tests have moved to the eigenverb/test directory.

But now, it is unclear to me how re-enable the original functionality of reflect_flat_test without also testing reverberation.  Probably not hard to do, I just have not taken the time to investigate.

**Comment by Tibonium** [comment]
Forgot to mention an important change to build_eigenverbs. The tracker for the number of bottom and surface interactions was always behind by one, this was due to the fact that the wavefront does not increment these values until after the call to reflection_model::****_reflection has taken place. Added logic to rectify this error.
