### ISSUE TITLE
Invalid array index in `data_grid_svp.h`

### ISSUE THREAD

**Issue by cconvey** [campreilly/UnderSeaModelingLibrary#265]
In the `data_grid_svp` class, a local variable is declared as an array of size 2:

https://github.com/campreilly/UnderSeaModelingLibrary/blob/226e335b1c17df66af9122b0c9111edc2065a0e5/types/data_grid_svp.h#L157

Later in that same method body, an invalid index into that array is used:

https://github.com/campreilly/UnderSeaModelingLibrary/blob/226e335b1c17df66af9122b0c9111edc2065a0e5/types/data_grid_svp.h#L217

That function also contains a loop which (based on my reading of the code) illegally *writes* to `offset[2]` during the loop's final iteration:

https://github.com/campreilly/UnderSeaModelingLibrary/blob/226e335b1c17df66af9122b0c9111edc2065a0e5/types/data_grid_svp.h#L169-L208

**Comment by campreilly** [comment]
Take a look at issue #257. I’m having some trouble with this class as well. The original purpose of this class was to speed up the calculation by avoiding the recursion implemented in gen_grid class. Basically hardcode one of our more commonly used interpolations instead of using the generic, all purpose algorithm. 

Note that I just recently made a change to use only “double” values in my grids instead of setting the payload type in using a template parameter. I’d be open to revisiting that decision if it made interpretation run faster.

**Comment by campreilly** [comment]
Fixed in pull request #226 Import changes from GUWA project.
