### ISSUE TITLE
infinite recursion in seq_vector.h

### ISSUE THREAD

**Issue by cconvey** [campreilly/UnderSeaModelingLibrary#276]
`clang++-17 -Wall ...` issues this warning:
```
/home/cconvey/r/cconvey/usml/usml/../usml/types/seq_vector.h:173:43: warning: all paths through this function will call itself [-Winfinite-recursion]
  173 |     const_reverse_iterator rbegin() const {
      |                                           ^
/home/cconvey/r/cconvey/usml/usml/../usml/types/seq_vector.h:180:41: warning: all paths through this function will call itself [-Winfinite-recursion]
  180 |     const_reverse_iterator rend() const {
      |                                         ^
2 warnings generated.
```

I wonder if this code can just be removed?  I'm assuming that it's not used, since people would notice the model hanging and/or blowing out the stack.

**Comment by campreilly** [comment]
I think the problem here is that the implementations should have used “_data.rbegin()” and “_data.rend()”. These interfaces were added so that sequences could exchange data with other containers and streams. But it’s been so long, I don’t even remember if the reverse iterators were critical to that functionality.
